all: zoomCalc zoomMonteCarlo

zoomCalc: zoomCalc.cpp zoomLib.cpp 
	g++ zoomCalc.cpp zoomLib.cpp -o zoomCalc

zoomMonteCarlo: zoomMonteCarlo.cpp zoomLib.cpp
	g++ zoomMonteCarlo.cpp zoomLib.cpp -o zoomMonte
